// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrhpWFVSm-KSSerDYU6B9ss-lrrJhgL64',
    appId: '1:284761605692:web:ae81fa785ed5ebaa1ae539',
    messagingSenderId: '284761605692',
    projectId: 'ernaehrungsplaner-bueny',
    authDomain: 'ernaehrungsplaner-bueny.firebaseapp.com',
    storageBucket: 'ernaehrungsplaner-bueny.firebasestorage.app',
    measurementId: 'G-6VEM630EZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCchJaDVH5pgrZhvM7_9Kl6_thypWeX_k',
    appId: '1:284761605692:android:b7c575d1e751be2c1ae539',
    messagingSenderId: '284761605692',
    projectId: 'ernaehrungsplaner-bueny',
    storageBucket: 'ernaehrungsplaner-bueny.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4_DrL3hrta7GKt0Hi1mJq1I6AD8i97po',
    appId: '1:284761605692:ios:06b25e7ad8bee5d61ae539',
    messagingSenderId: '284761605692',
    projectId: 'ernaehrungsplaner-bueny',
    storageBucket: 'ernaehrungsplaner-bueny.firebasestorage.app',
    iosBundleId: 'com.example.ernaehrungsplaner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4_DrL3hrta7GKt0Hi1mJq1I6AD8i97po',
    appId: '1:284761605692:ios:06b25e7ad8bee5d61ae539',
    messagingSenderId: '284761605692',
    projectId: 'ernaehrungsplaner-bueny',
    storageBucket: 'ernaehrungsplaner-bueny.firebasestorage.app',
    iosBundleId: 'com.example.ernaehrungsplaner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrhpWFVSm-KSSerDYU6B9ss-lrrJhgL64',
    appId: '1:284761605692:web:d6a805d2c751c0531ae539',
    messagingSenderId: '284761605692',
    projectId: 'ernaehrungsplaner-bueny',
    authDomain: 'ernaehrungsplaner-bueny.firebaseapp.com',
    storageBucket: 'ernaehrungsplaner-bueny.firebasestorage.app',
    measurementId: 'G-1MMBGB8MB1',
  );
}
